### ISSUE TITLE
Adapt Schemable generation script to include `WithRefine` typeclasses, instance import from `InstanceBase`, and spread on its `Schemable` instance

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemable-ts-types#107]
All the instances (Decoder, Encoder, etc) need to import their respective `With` typeclass instances and spread on their `SchemableExt` instance.  This needs to be adapted in the generate-schemable script.  It could probably stand to use some cleanup if so inclined.

**Comment by jacob-alford** [comment]
Only thing left is `WithRefine` currently in progress in PR: #113 and issue: #105

**Comment by skeate** [comment]
merged in 1.0
