### ISSUE TITLE
Add more fine-grained `number` helpers

### ISSUE THREAD

**Issue by skeate** [jacob-alford/schemable-ts-types#114]
Thinking `int({ min, max })` and `float({ min, max })` can cover all the cases that exist in `src/number`

**Comment by jacob-alford** [comment]
Instead of making these helpers, we could keep the `Int` and `float` modules, and use `refine` and `brand` to derive the others, like PositiveInt

**Comment by skeate** [comment]
Actually yeah, we don't even need explicit int/float, `number` + `refine` + `brand` does it all

**Comment by skeate** [comment]
(though it means more churn in the `Arbitrary` case....)

**Comment by jacob-alford** [comment]
That's a great point, I didn't think about the Arbitrary case.

I would say, let's adjust the number > int and number > float modules to accept `{ min, max }` and possibly with sensible defaults like MIN/MAX_SAFE_INTEGER or +-MAX_VALUE

**Comment by jacob-alford** [comment]
Made a ticket for it:

#124

**Comment by skeate** [comment]
:sweat_smile: what was wrong with this one

**Comment by jacob-alford** [comment]
Either way lol, I just made a ticket in the project.  I forgot you can add it from the issue view

**Comment by skeate** [comment]
dupe of #124 which has less noise
