### ISSUE TITLE
Create PatternBuilder Regex printer combinators

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemable-ts-types#117]
Completely @skeate’s idea: create PatternBuilder combinators for constructing regex’s which can be used as Schemable combinators within Arbitrary.

Will greatly reduce the amount of code necessary, and eliminate many of the `string` combinator modules to be moved to the `schemas` folder for re-export in the `schemas` directory.  

The final idea is to have two imports, the first with all predefined Schemas, the second with interpreters:

```typescript
import * as S from ‘schemable-ts-types/schemas’
import * as I from ‘schemable-ts-types/interpreters’

const User = S.Struct({
  id: S.UUID({ version: 5 }),
  email: S.Email,
  username: S.ASCII,
  favouriteColour: S.HexColor
})

export type User = S.TypeOf<typeof User>

const decodeUser = I.interpret(I.Decoder)(User)
const guardUser = I.interpret(I.Guard)(User)
const eqUser = I.interpret(I.Eq)(User)
const taskDecoderUser = I.interpret(I.TaskDecoder)(User)
const arbitraryUser = I.interpret(I.Arbitrary)(User)
```

**Comment by skeate** [comment]
closing as it's merged in 1.0 branch
