### ISSUE TITLE
Add CreditCard string module

### ISSUE THREAD

**Issue by newswim** [jacob-alford/schemable-ts-types#14]
See: https://github.com/validatorjs/validator.js/blob/master/src/lib/isCreditCard.js

**Comment by jacob-alford** [comment]
This is large because it also depends on the "Luhn Algorithm".

Here are some resources:

- https://www.dcode.fr/luhn-algorithm
- https://github.com/validatorjs/validator.js/blob/master/src/lib/isLuhnValid.js
