### ISSUE TITLE
Refactor existing tests

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemable-ts-types#36]
Many of the existing tests are written hastily, and need to be updated with test-strength parity to validator.js.  There are some new test-utils available that makes bulk testing easy in #35

**Comment by skeate** [comment]
can you elaborate on this

**Comment by jacob-alford** [comment]
We only recently started using test cases from validators.js, and even more recently added fast-check.  The tests I added initially can be greatly simplified using the newer techniques, and/or fast-check.  

I think it's a good idea just to have a wider safety net.  

I think this is a massive ticket, so maybe it's worth it to break up module by module
